### CONFIGIGURACION

In [1]:
#para evitar posibles errores en el codigo:
import warnings
warnings.filterwarnings("ignore")

In [1]:
#crear el entorno virtual
! python -m venv Entorno_proyect_final

In [3]:
#activar el entorno virtual
! .\Entorno_proyect_final\Scripts\Activate

In [ ]:
#instalacion de librerias y dependencias al entorno
#! pip install -r .\requerimientos.txt

In [ ]:
# obserbar que tengo yo 
! pip freeze

In [3]:
#para actualizar las librerias en el txt.
! pip freeze > .\requerimientos.txt

In [2]:
# Carga de librerias 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

### Apertura data

In [3]:
# Obtener el directorio de trabajo actual ( este paso si es necesario)
directorio_actual = os.getcwd()
print(f"Directorio de trabajo actual: {directorio_actual}")

Directorio de trabajo actual: c:\Users\beren\Desktop\HENRRY\G4_Inventory

### SQL SERVER

In [2]:
# en la notepad que se abrira hay que colocar:
''' 
DB_USER= "..."
DB_NAME= "..."
DB_HOST=localhost
DB_PASSWORD=mi_contraseña_secreta
DB_PORT=1433 '''

! notepad .env

### Coneccion a Base de datos y cracion de la base de datos:

In [ ]:
#sin contraseña autenticacion windows
import pyodbc
import os
from dotenv import load_dotenv

# Cargar las variables de entorno desde el archivo .env
load_dotenv()

# Obtener las variables de entorno
hostname = os.getenv("DB_HOST")
db = os.getenv("DB_NAME")

# Cadena de conexión usando autenticación integrada de Windows
connection = pyodbc.connect(f'DRIVER={{SQL Server}};SERVER={hostname};DATABASE={db};Trusted_Connection=yes')

# Verificar la conexión
print("Conexión exitosa a la base de datos")

# Crear un cursor para ejecutar consultas
cursor = connection.cursor()

# Aquí puedes comenzar a ejecutar tus consultas usando el cursor

In [5]:
cursor.close()
connection.close()

In [4]:
#autenticacion SQLserver
import pyodbc
import os
from dotenv import load_dotenv

# Cargar las variables de entorno desde el archivo .env
load_dotenv()

# Obtener las variables de entorno
hostname = os.getenv("DB_HOST")
db = os.getenv("DB_NAME")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")

# Cadena de conexión usando usuario y contraseña
connection = pyodbc.connect(f'DRIVER={{SQL Server}};SERVER={hostname};DATABASE={db};UID={user};PWD={password}')

# Verificar la conexión
print("Conexión exitosa a la base de datos")

# Crear un cursor para ejecutar consultas
cursor = connection.cursor()

Conexión exitosa a la base de datos

In [5]:
# Diccionario con los nombres de los archivos
archivos = {
    'precios_compra_dic': r"archive\2017PurchasePricesDec.csv",
    'Inicio_Inv_FINAL': r"archive\BegInvFINAL12312016.csv",
    'final_inv_Final': r"archive\EndInvFINAL12312016.csv",
    'Factura_Compras': r"archive\InvoicePurchases12312016.csv",
    'Compras_Finales': r"archive\PurchasesFINAL12312016.csv",
    'Ventas_Final': r"archive\SalesFINAL12312016.csv"
}

# Leer y mostrar las primeras 5 filas de cada archivo
for nombre, ruta in archivos.items():
    ruta_archivo = os.path.join(directorio_actual, ruta)
    # Verificar si el archivo existe antes de intentar leerlo
    if os.path.exists(ruta_archivo):
        df = pd.read_csv(ruta_archivo)
        print(f"\n{nombre}:\n", df)
    else:
        print(f"El archivo {ruta_archivo} no existe.")

precios_compra_dic:
        Brand                   Description  Price    Size Volume  \
0         58   Gekkeikan Black & Gold Sake  12.99   750mL    750
1         62      Herradura Silver Tequila  36.99   750mL    750
2         63    Herradura Reposado Tequila  38.99   750mL    750
3         72          No. 3 London Dry Gin  34.99   750mL    750
4         75     Three Olives Tomato Vodka  14.99   750mL    750
...      ...                           ...    ...     ...    ...
12256  44917     Ferreira 10-Yr Tawny Port  24.99   750mL    750
12257  44944     Sanford Santa Rita Pnt Nr  22.99   750mL    750
12258  45016  Neal One Lane Bridg Cab Svgn  93.99   750mL    750
12259  46011       Folonari Pnt Nr Venezie  12.99  1500ml   1500
12260  46964     Calera Viognier Mt Harlan  35.99   750mL    750

       Classification  PurchasePrice  VendorNumber  \
0                   1           9.28          8320
1                   1          28.67          1128
2                   1          30.46          1128
3                   1          26.11          9165
4                   1          10.94          7245
...               ...            ...           ...
12256               2          16.55         90024
12257               2          14.93          4425
12258               2          61.43         10754
12259               2           8.90          9744
12260               2          24.32         10754

                        VendorName
0      SHAW ROSS INT L IMP LTD
1      BROWN-FORMAN CORP
2      BROWN-FORMAN CORP
3      ULTRA BEVERAGE COMPANY LLP
4      PROXIMO SPIRITS INC.
...                            ...
12256  VINILANDIA USA
12257        MARTIGNETTI COMPANIES
12258  PERFECTA WINES
12259  FREDERICK WILDMAN & SONS
12260  PERFECTA WINES

[12261 rows x 9 columns]

Inicio_Inv_FINAL:
                InventoryId  Store          City  Brand  \
0        1_HARDERSFIELD_58      1  HARDERSFIELD     58
1        1_HARDERSFIELD_60      1  HARDERSFIELD     60
2        1_HARDERSFIELD_62      1  HARDERSFIELD     62
3        1_HARDERSFIELD_63      1  HARDERSFIELD     63
4        1_HARDERSFIELD_72      1  HARDERSFIELD     72
...                    ...    ...           ...    ...
206524  79_BALLYMENA_46985     79     BALLYMENA  46985
206525  79_BALLYMENA_47014     79     BALLYMENA  47014
206526  79_BALLYMENA_47090     79     BALLYMENA  47090
206527  79_BALLYMENA_90011     79     BALLYMENA  90011
206528  79_BALLYMENA_90089     79     BALLYMENA  90089

                         Description   Size  onHand   Price   startDate
0        Gekkeikan Black & Gold Sake  750mL       8   12.99  2016-01-01
1             Canadian Club 1858 VAP  750mL       7   10.99  2016-01-01
2           Herradura Silver Tequila  750mL       6   36.99  2016-01-01
3         Herradura Reposado Tequila  750mL       3   38.99  2016-01-01
4               No. 3 London Dry Gin  750mL       6   34.99  2016-01-01
...                              ...    ...     ...     ...         ...
206524  Rodney Strong Cab Svgn Alexa  750mL      13   22.99  2016-01-01
206525           Juan Gil Jumilla Rd  750mL      13   13.99  2016-01-01
206526    Napa Cellars Cab Svgn Napa  750mL      19   23.99  2016-01-01
206527  Ch Pichon Longville 12 Pauil  750mL      12  144.99  2016-01-01
206528    Ch Lynch Bages 12 Pauillac  750mL      24  119.99  2016-01-01

[206529 rows x 9 columns]

final_inv_Final:
               InventoryId  Store          City  Brand  \
0       1_HARDERSFIELD_58      1  HARDERSFIELD     58
1       1_HARDERSFIELD_62      1  HARDERSFIELD     62
2       1_HARDERSFIELD_63      1  HARDERSFIELD     63
3       1_HARDERSFIELD_72      1  HARDERSFIELD     72
4       1_HARDERSFIELD_75      1  HARDERSFIELD     75
...                   ...    ...           ...    ...
224484  81_PEMBROKE_90087     81      PEMBROKE  90087
224485  81_PEMBROKE_90088     81      PEMBROKE  90088
224486  81_PEMBROKE_90089     81      PEMBROKE  90089
224487  81_PEMBROKE_90090     81      PEMBROKE  90090
224488  81_PEMBROKE_90604     81      PEMBROKE  90604

                         Description   Size  onHand   Price     endDate
0        Gekkeikan Black & Gold Sake  750mL      11   12.99  2016-12-31
1           Herradura Silver Tequila  750mL       7   36.99  2016-12-31
2         Herradura Reposado Tequila  750mL       7   38.99  2016-12-31
3               No. 3 London Dry Gin  750mL       4   34.99  2016-12-31
4          Three Olives Tomato Vodka  750mL       7   14.99  2016-12-31
...                              ...    ...     ...     ...         ...
224484  Ch Mouton Rothschild 12 Paui  750mL       3  469.99  2016-12-31
224485  Ch Le Petite Mouton 12 Pauil  750mL       3  134.99  2016-12-31
224486    Ch Lynch Bages 12 Pauillac  750mL       3  119.99  2016-12-31
224487       Ch Lafite Rothschild 12  750mL       3  649.99  2016-12-31
224488        Ch Lynch Bages Pauilac  750mL       2  119.99  2016-12-31

[224489 rows x 9 columns]

Factura_Compras:
       VendorNumber                   VendorName InvoiceDate  PONumber  \
0              105  ALTAMAR BRANDS LLC           2016-01-04      8124
1             4466  AMERICAN VINTAGE BEVERAGE    2016-01-07      8137
2              388  ATLANTIC IMPORTING COMPANY   2016-01-09      8169
3              480  BACARDI USA INC              2016-01-12      8106
4              516  BANFI PRODUCTS CORP          2016-01-07      8170
...            ...                          ...         ...       ...
5538          9622  WEIN BAUER INC               2017-01-06     13626
5539          9625  WESTERN SPIRITS BEVERAGE CO  2017-01-10     13661
5540          3664  WILLIAM GRANT & SONS INC     2017-01-02     13643
5541          9815  WINE GROUP INC               2017-01-03     13602
5542         90058  ZORVINO VINEYARDS            2017-01-05     13574

          PODate     PayDate  Quantity    Dollars  Freight Approval
0     2015-12-21  2016-02-16         6     214.26     3.47      NaN
1     2015-12-22  2016-02-21        15     140.55     8.57      NaN
2     2015-12-24  2016-02-16         5     106.60     4.61      NaN
3     2015-12-20  2016-02-05     10100  137483.78  2935.20      NaN
4     2015-12-24  2016-02-12      1935   15527.25   429.20      NaN
...          ...         ...       ...        ...      ...      ...
5538  2016-12-21  2017-02-10        90    1563.00     8.60      NaN
5539  2016-12-23  2017-02-18      4617   37300.48   186.50      NaN
5540  2016-12-22  2017-02-04      9848  202815.78   932.95      NaN
5541  2016-12-20  2017-02-08     24747  149007.56   819.54      NaN
5542  2016-12-18  2017-02-12       437    3608.11    16.60      NaN

[5543 rows x 10 columns]

Compras_Finales:
                   InventoryId  Store  Brand                   Description  \
0           69_MOUNTMEND_8412     69   8412     Tequila Ocho Plata Fresno
1            30_CULCHETH_5255     30   5255  TGI Fridays Ultimte Mudslide
2           34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced
3         1_HARDERSFIELD_5255      1   5255  TGI Fridays Ultimte Mudslide
4           76_DONCASTER_2034     76   2034     Glendalough Double Barrel
...                       ...    ...    ...                           ...
2372469     49_GARIGILL_22298     49  22298       Zorvino Vyds Sangiovese
2372470  1_HARDERSFIELD_19556      1  19556    Zorvino Bacca Z Blackberry
2372471   66_EANVERNESS_22297     66  22297            Zorvino Vyds Pearz
2372472    69_MOUNTMEND_19557     69  19557  Zorvino Fragole Z Strawberry
2372473    55_DRY GULCH_22298     55  22298       Zorvino Vyds Sangiovese

          Size  VendorNumber                   VendorName  PONumber  \
0        750mL           105  ALTAMAR BRANDS LLC               8124
1        1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137
2        1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137
3        1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137
4        750mL           388  ATLANTIC IMPORTING COMPANY       8169
...        ...           ...                          ...       ...
2372469  750mL         90058  ZORVINO VINEYARDS               13593
2372470  750mL         90058  ZORVINO VINEYARDS               13593
2372471  750mL         90058  ZORVINO VINEYARDS               13593
2372472  750mL         90058  ZORVINO VINEYARDS               13593
2372473  750mL         90058  ZORVINO VINEYARDS               13593

             PODate ReceivingDate InvoiceDate     PayDate  PurchasePrice  \
0        2015-12-21    2016-01-02  2016-01-04  2016-02-16          35.71
1        2015-12-22    2016-01-01  2016-01-07  2016-02-21           9.35
2        2015-12-22    2016-01-02  2016-01-07  2016-02-21           9.41
3        2015-12-22    2016-01-01  2016-01-07  2016-02-21           9.35
4        2015-12-24    2016-01-02  2016-01-09  2016-02-16          21.32
...             ...           ...         ...         ...            ...
2372469  2016-12-19    2016-12-28  2017-01-09  2017-02-06           8.06
2372470  2016-12-19    2016-12-27  2017-01-09  2017-02-06           9.39
2372471  2016-12-19    2016-12-26  2017-01-09  2017-02-06           6.75
2372472  2016-12-19    2016-12-26  2017-01-09  2017-02-06           9.39
2372473  2016-12-19    2016-12-28  2017-01-09  2017-02-06           8.06

         Quantity  Dollars  Classification
0               6   214.26               1
1               4    37.40               1
2               5    47.05               1
3               6    56.10               1
4               5   106.60               1
...           ...      ...             ...
2372469        12    96.72               2
2372470        12   112.68               2
2372471        12    81.00               2
2372472        12   112.68               2
2372473        12    96.72               2

[2372474 rows x 16 columns]

Ventas_Final:
                  InventoryId  Store  Brand                 Description  \
0        1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
1        1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
2        1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
3        1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
4        1_HARDERSFIELD_1005      1   1005     Maker's Mark Combo Pack
...                      ...    ...    ...                         ...
1048570  19_WINTERVALE_39384     19  39384    F Coppola Diamond Pnt Nr
1048571  19_WINTERVALE_39384     19  39384    F Coppola Diamond Pnt Nr
1048572  19_WINTERVALE_39384     19  39384    F Coppola Diamond Pnt Nr
1048573  19_WINTERVALE_39384     19  39384    F Coppola Diamond Pnt Nr
1048574  19_WINTERVALE_39384     19  39384    F Coppola Diamond Pnt Nr

               Size  SalesQuantity  SalesDollars  SalesPrice  SalesDate  \
0             750mL              1         16.49       16.49   1/1/2016
1             750mL              2         32.98       16.49   1/2/2016
2             750mL              1         16.49       16.49   1/3/2016
3             750mL              1         14.49       14.49   1/8/2016
4        375mL 2 Pk              2         69.98       34.99   1/9/2016
...             ...            ...           ...         ...        ...
1048570       750mL              4         51.80       12.95  2/12/2016
1048571       750mL              8        103.60       12.95  2/13/2016
1048572       750mL              1         12.95       12.95  2/19/2016
1048573       750mL              3         38.85       12.95  2/22/2016
1048574       750mL              2         25.90       12.95  2/24/2016

         Volume  Classification  ExciseTax  VendorNo  \
0           750               1       0.79     12546
1           750               1       1.57     12546
2           750               1       0.79     12546
3           750               1       0.79     12546
4           375               1       0.79     12546
...         ...             ...        ...       ...
1048570     750               2       0.45      2000
1048571     750               2       0.90      2000
1048572     750               2       0.11      2000
1048573     750               2       0.34      2000
1048574     750               2       0.22      2000

                          VendorName
0        JIM BEAM BRANDS COMPANY
1        JIM BEAM BRANDS COMPANY
2        JIM BEAM BRANDS COMPANY
3        JIM BEAM BRANDS COMPANY
4        JIM BEAM BRANDS COMPANY
...                              ...
1048570  SOUTHERN WINE & SPIRITS NE
1048571  SOUTHERN WINE & SPIRITS NE
1048572  SOUTHERN WINE & SPIRITS NE
1048573  SOUTHERN WINE & SPIRITS NE
1048574  SOUTHERN WINE & SPIRITS NE

[1048575 rows x 14 columns]

In [6]:
# Leer, contar filas y limpiar nulos de cada archivo
for nombre, ruta in archivos.items():
    ruta_archivo = os.path.join(directorio_actual, ruta)
    
    # Verificar si el archivo existe antes de intentar leerlo
    if os.path.exists(ruta_archivo):
        # Leer el archivo CSV
        df = pd.read_csv(ruta_archivo)
        
        # Contar filas antes de eliminar nulos
        filas_originales = df.shape[0]
        
        # Eliminar filas con nulos
        df_limpio = df.dropna()
        
        # Contar filas después de eliminar nulos
        filas_limpias = df_limpio.shape[0]
        
        # Imprimir resultados
        print(f"\n{nombre}:")
        print(f"Total de filas originales: {filas_originales}")
        print(f"Total de filas después de eliminar nulos: {filas_limpias}")
        
    else:
        print(f"El archivo {ruta_archivo} no existe.")

precios_compra_dic:
Total de filas originales: 12261
Total de filas después de eliminar nulos: 12260

Inicio_Inv_FINAL:
Total de filas originales: 206529
Total de filas después de eliminar nulos: 206529

final_inv_Final:
Total de filas originales: 224489
Total de filas después de eliminar nulos: 223205

Factura_Compras:
Total de filas originales: 5543
Total de filas después de eliminar nulos: 374

Compras_Finales:
Total de filas originales: 2372474
Total de filas después de eliminar nulos: 2372471

Ventas_Final:
Total de filas originales: 1048575
Total de filas después de eliminar nulos: 1048575

In [12]:
# Función para crear tabla si no existe
def create_table_if_not_exists(create_table_sql):
    # Ejecutar la consulta para verificar si la tabla existe
    table_name = create_table_sql.split()[2]  # Obtener el nombre de la tabla
    check_table_sql = f'''
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '{table_name}')
    BEGIN
        {create_table_sql}
    END
    '''
    cursor.execute(check_table_sql)

# Definir las consultas SQL para crear las tablas
create_precios_compra_dic = '''
CREATE TABLE precios_compra_dic (
    Brand INT,
    Description VARCHAR(255),
    Price FLOAT,
    Size VARCHAR(255),
    volume INT,
    Classification INT,
    PurchasePrice FLOAT,
    VendorNumber INT,
    VendorName VARCHAR(255)
);
'''

create_inicio_inv_final = '''
CREATE TABLE Inicio_Inv_FINAL (
    InventoryId VARCHAR(255),
    Store INT,
    City VARCHAR(255),
    Brand INT,
    Description VARCHAR(255),
    Size VARCHAR(255),
    onHand INT,
    Price FLOAT,
    startDate DATE
);
'''

create_final_inv_final = '''
CREATE TABLE final_inv_Final (
    InventoryId VARCHAR(255),
    Store INT,
    City VARCHAR(255),
    Brand INT,
    Description VARCHAR(255),
    Size VARCHAR(255),
    onHand INT,
    Price FLOAT,
    endDate DATE
);
'''

create_factura_compras = '''
CREATE TABLE Factura_Compras (
    VendorNumber INT,
    VendorName VARCHAR(255),
    InvoiceDate DATE,
    PONumber INT,
    PODate DATE,
    PayDate DATE,
    Quantity INT,
    Dollars FLOAT,
    Freight FLOAT,
    Approval FLOAT
);
'''

create_compras_finales = '''
CREATE TABLE Compras_Finales (
    InventoryId VARCHAR(255),
    Store INT,
    Brand INT,
    Description VARCHAR(255),
    Size VARCHAR(255),
    VendorNumber INT,
    VendorName VARCHAR(255),
    PONumber INT,
    PODate DATE,
    ReceivingDate DATE,
    InvoiceDate DATE,
    PayDate DATE,
    PurchasePrice FLOAT,
    Quantity INT,
    Dollars FLOAT,
    Classification INT
);
'''

create_ventas_final = '''
CREATE TABLE Ventas_Final (
    InventoryId VARCHAR(255),
    Store INT,
    Brand INT,
    Description VARCHAR(255),
    Size VARCHAR(255),
    SalesQuantity INT,
    SalesDollars FLOAT,
    SalesPrice FLOAT,
    SalesDate DATE,
    Volume INT,
    Classification INT,
    ExciseTax FLOAT,
    VendorNo INT,
    VendorName VARCHAR(255)
);
'''

# Ejecutar las consultas para crear las tablas si no existen
create_table_if_not_exists(create_precios_compra_dic)
create_table_if_not_exists(create_inicio_inv_final)
create_table_if_not_exists(create_final_inv_final)
create_table_if_not_exists(create_factura_compras)
create_table_if_not_exists(create_compras_finales)
create_table_if_not_exists(create_ventas_final)

# Confirmar cambios en la base de datos
connection.commit()

# Cerrar el cursor y la conexión
cursor.close()
connection.close()

print("Tablas creadas exitosamente si no existían.")

Tablas creadas exitosamente si no existían.

In [12]:
# Cargar los DataFrames
dataframes = {}
for nombre, archivo in archivos.items():
    dataframes[nombre] = pd.read_csv(archivo)

# Función para manejar las conversiones con errores
def safe_convert(df, column, dtype):
    if dtype == 'int':
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0).astype(int)
    elif dtype == 'float':
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0.0).astype(float)
    else:
        df[column] = df[column].astype(dtype)

# precios_compra_dic
safe_convert(dataframes['precios_compra_dic'], 'Brand', 'int')
dataframes['precios_compra_dic']['Description'] = dataframes['precios_compra_dic']['Description'].astype(str)
safe_convert(dataframes['precios_compra_dic'], 'Price', 'float')
dataframes['precios_compra_dic']['Size'] = dataframes['precios_compra_dic']['Size'].astype(str)
safe_convert(dataframes['precios_compra_dic'], 'Volume', 'int')
safe_convert(dataframes['precios_compra_dic'], 'Classification', 'int')
safe_convert(dataframes['precios_compra_dic'], 'PurchasePrice', 'float')
safe_convert(dataframes['precios_compra_dic'], 'VendorNumber', 'int')
dataframes['precios_compra_dic']['VendorName'] = dataframes['precios_compra_dic']['VendorName'].astype(str)

# Inicio_Inv_FINAL
dataframes['Inicio_Inv_FINAL']['InventoryId'] = dataframes['Inicio_Inv_FINAL']['InventoryId'].astype(str)
safe_convert(dataframes['Inicio_Inv_FINAL'], 'Store', 'int')
dataframes['Inicio_Inv_FINAL']['City'] = dataframes['Inicio_Inv_FINAL']['City'].astype(str)
safe_convert(dataframes['Inicio_Inv_FINAL'], 'Brand', 'int')
dataframes['Inicio_Inv_FINAL']['Description'] = dataframes['Inicio_Inv_FINAL']['Description'].astype(str)
dataframes['Inicio_Inv_FINAL']['Size'] = dataframes['Inicio_Inv_FINAL']['Size'].astype(str)
safe_convert(dataframes['Inicio_Inv_FINAL'], 'onHand', 'int')
safe_convert(dataframes['Inicio_Inv_FINAL'], 'Price', 'float')
dataframes['Inicio_Inv_FINAL']['startDate'] = pd.to_datetime(dataframes['Inicio_Inv_FINAL']['startDate'], errors='coerce')

# final_inv_Final
dataframes['final_inv_Final']['InventoryId'] = dataframes['final_inv_Final']['InventoryId'].astype(str)
safe_convert(dataframes['final_inv_Final'], 'Store', 'int')
dataframes['final_inv_Final']['City'] = dataframes['final_inv_Final']['City'].astype(str)
safe_convert(dataframes['final_inv_Final'], 'Brand', 'int')
dataframes['final_inv_Final']['Description'] = dataframes['final_inv_Final']['Description'].astype(str)
dataframes['final_inv_Final']['Size'] = dataframes['final_inv_Final']['Size'].astype(str)
safe_convert(dataframes['final_inv_Final'], 'onHand', 'int')
safe_convert(dataframes['final_inv_Final'], 'Price', 'float')
dataframes['final_inv_Final']['endDate'] = pd.to_datetime(dataframes['final_inv_Final']['endDate'], errors='coerce')

# Factura_Compras
safe_convert(dataframes['Factura_Compras'], 'VendorNumber', 'int')
dataframes['Factura_Compras']['VendorName'] = dataframes['Factura_Compras']['VendorName'].astype(str)
dataframes['Factura_Compras']['InvoiceDate'] = pd.to_datetime(dataframes['Factura_Compras']['InvoiceDate'], errors='coerce')
safe_convert(dataframes['Factura_Compras'], 'PONumber', 'int')
dataframes['Factura_Compras']['PODate'] = pd.to_datetime(dataframes['Factura_Compras']['PODate'], errors='coerce')
dataframes['Factura_Compras']['PayDate'] = pd.to_datetime(dataframes['Factura_Compras']['PayDate'], errors='coerce')
safe_convert(dataframes['Factura_Compras'], 'Quantity', 'int')
safe_convert(dataframes['Factura_Compras'], 'Dollars', 'float')
safe_convert(dataframes['Factura_Compras'], 'Freight', 'float')
safe_convert(dataframes['Factura_Compras'], 'Approval', 'float')

# Compras_Finales
dataframes['Compras_Finales']['InventoryId'] = dataframes['Compras_Finales']['InventoryId'].astype(str)
safe_convert(dataframes['Compras_Finales'], 'Store', 'int')
safe_convert(dataframes['Compras_Finales'], 'Brand', 'int')
dataframes['Compras_Finales']['Description'] = dataframes['Compras_Finales']['Description'].astype(str)
dataframes['Compras_Finales']['Size'] = dataframes['Compras_Finales']['Size'].astype(str)
safe_convert(dataframes['Compras_Finales'], 'VendorNumber', 'int')
dataframes['Compras_Finales']['VendorName'] = dataframes['Compras_Finales']['VendorName'].astype(str)
safe_convert(dataframes['Compras_Finales'], 'PONumber', 'int')
dataframes['Compras_Finales']['PODate'] = pd.to_datetime(dataframes['Compras_Finales']['PODate'], errors='coerce')
dataframes['Compras_Finales']['ReceivingDate'] = pd.to_datetime(dataframes['Compras_Finales']['ReceivingDate'], errors='coerce')
dataframes['Compras_Finales']['InvoiceDate'] = pd.to_datetime(dataframes['Compras_Finales']['InvoiceDate'], errors='coerce')
dataframes['Compras_Finales']['PayDate'] = pd.to_datetime(dataframes['Compras_Finales']['PayDate'], errors='coerce')
safe_convert(dataframes['Compras_Finales'], 'PurchasePrice', 'float')
safe_convert(dataframes['Compras_Finales'], 'Quantity', 'int')
safe_convert(dataframes['Compras_Finales'], 'Dollars', 'float')
safe_convert(dataframes['Compras_Finales'], 'Classification', 'int')

# Ventas_Final
dataframes['Ventas_Final']['InventoryId'] = dataframes['Ventas_Final']['InventoryId'].astype(str)
safe_convert(dataframes['Ventas_Final'], 'Store', 'int')
safe_convert(dataframes['Ventas_Final'], 'Brand', 'int')
dataframes['Ventas_Final']['Description'] = dataframes['Ventas_Final']['Description'].astype(str)
dataframes['Ventas_Final']['Size'] = dataframes['Ventas_Final']['Size'].astype(str)
safe_convert(dataframes['Ventas_Final'], 'SalesQuantity', 'int')
safe_convert(dataframes['Ventas_Final'], 'SalesDollars', 'float')
safe_convert(dataframes['Ventas_Final'], 'SalesPrice', 'float')
dataframes['Ventas_Final']['SalesDate'] = pd.to_datetime(dataframes['Ventas_Final']['SalesDate'], errors='coerce')
safe_convert(dataframes['Ventas_Final'], 'Volume', 'int')
safe_convert(dataframes['Ventas_Final'], 'Classification', 'int')
safe_convert(dataframes['Ventas_Final'], 'ExciseTax', 'float')
safe_convert(dataframes['Ventas_Final'], 'VendorNo', 'int')
dataframes['Ventas_Final']['VendorName'] = dataframes['Ventas_Final']['VendorName'].astype(str)

* insertar solo una vez para que no se repitan los datos!

In [15]:
#import pandas as pd
from sqlalchemy import create_engine

# Crear la cadena de conexión para SQLAlchemy
connection_string = f'mssql+pyodbc://{user}:{password}@{hostname}/{db}?driver=ODBC+Driver+17+for+SQL+Server'

# Crear un motor de SQLAlchemy
engine = create_engine(connection_string)

# Insertar datos en las tablas
dataframes['precios_compra_dic'].to_sql('precios_compra_dic', con=engine, if_exists='append', index=False)
dataframes['Inicio_Inv_FINAL'].to_sql('Inicio_Inv_FINAL', con=engine, if_exists='append', index=False)
dataframes['final_inv_Final'].to_sql('final_inv_Final', con=engine, if_exists='append', index=False)
dataframes['Factura_Compras'].to_sql('Factura_Compras', con=engine, if_exists='append', index=False)
dataframes['Compras_Finales'].to_sql('Compras_Finales', con=engine, if_exists='append', index=False)
dataframes['Ventas_Final'].to_sql('Ventas_Final', con=engine, if_exists='append', index=False)

print("Datos insertados exitosamente en las tablas.")

Datos insertados exitosamente en las tablas.